name: CI/CD Pipeline

on:
  push:
    branches: [main]  # Ana dalınızı belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Klonla
      uses: actions/checkout@v3

    - name: Sunucuya Bağlan ve Deploy Et
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 161.35.12.199
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/jeetnuxtcmsv1
          git pull
          npm install
          npm run build
          pm2 restart jeetnuxtcmsv1
